buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.23"  // Updated to Kotlin 1.9.23
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:1.9.23-1.0.19"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
