package com.chezpaul.model

data class BoissonConfig(
    val nom: String,
    val categorie: CategorieBoisson,
    val isGroupe: Boolean,
    val isNonGroupe: Boolean,
    val isActivated: Boolean = true,
    val sousCategorie: String? = null,
    val prix: Double = 0.0,
)

val boissonsList =
    listOf(
        // Apéros
        BoissonConfig("Kir", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Communard", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Ricard", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Whisky", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Pastis", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Campari", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Campari Orange", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 7.0),
        BoissonConfig("Martini Rouge", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Martini Blanc", CategorieBoisson.APEROS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        // Digestifs
        BoissonConfig("Chartreuse jaune", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Chartreuse verte", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Genepi", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Genereuse", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Verveine", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Menthe", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Poire", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Mandarine", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Abricot", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Marc", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Grillotine", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Mirabelle", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Rhum", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        BoissonConfig("Episcopal", CategorieBoisson.DIGESTIFS, isGroupe = false, isNonGroupe = true, prix = 9.0),
        // Bières
        BoissonConfig("Blonde 33cl", CategorieBoisson.BIERES, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Blanche 33cl", CategorieBoisson.BIERES, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Sans alcool 33cl", CategorieBoisson.BIERES, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Rousse 33cl", CategorieBoisson.BIERES, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Demi", CategorieBoisson.BIERES, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Pinte", CategorieBoisson.BIERES, isGroupe = false, isNonGroupe = true, prix = 10.0),
        // Softs
        BoissonConfig("Sirop", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 2.50),
        BoissonConfig("Limonade", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 5.0),
        BoissonConfig("Ice Tea", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 5.0),
        BoissonConfig("Coca", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 5.0),
        BoissonConfig("Orange", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 5.0),
        BoissonConfig("ACE", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 5.0),
        BoissonConfig("Fraise", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 5.0),
        BoissonConfig("Badoit", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Evian", CategorieBoisson.SOFTS, isGroupe = false, isNonGroupe = true, prix = 6.0),
        // Vins Fontaine
        BoissonConfig("Morgon Pot", CategorieBoisson.VINS_FONTAINE, isGroupe = true, isNonGroupe = true, prix = 16.0),
        BoissonConfig("Morgon Filette", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 8.0),
        BoissonConfig("Morgon Verre", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("CDR Pot", CategorieBoisson.VINS_FONTAINE, isGroupe = true, isNonGroupe = true, prix = 16.0),
        BoissonConfig("CDR Filette", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 8.0),
        BoissonConfig("CDR Verre", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Blanc Pot", CategorieBoisson.VINS_FONTAINE, isGroupe = true, isNonGroupe = true, prix = 16.0),
        BoissonConfig("Blanc Filette", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 8.0),
        BoissonConfig("Blanc Verre", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 6.0),
        BoissonConfig("Rose Pot", CategorieBoisson.VINS_FONTAINE, isGroupe = true, isNonGroupe = true, prix = 16.0),
        BoissonConfig("Rose Filette", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 8.0),
        BoissonConfig("Rose Verre", CategorieBoisson.VINS_FONTAINE, isGroupe = false, isNonGroupe = true, prix = 6.0),
        // Vins Bouteilles - Rouge
        BoissonConfig(
            "Cote Rotie",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Rouge",
            prix = 79.0,
        ),
        BoissonConfig(
            "Saint Joseph",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Rouge",
            prix = 37.50,
        ),
        BoissonConfig(
            "Crozes",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Rouge",
            prix = 35.0,
        ),
        BoissonConfig(
            "Régnié",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Rouge",
            prix = 30.0,
        ),
        BoissonConfig(
            "Village",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Rouge",
            prix = 24.0,
        ),
        BoissonConfig(
            "Bourgogne",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Rouge",
            prix = 29.0,
        ),
        // Vins Bouteilles - Blanc
        BoissonConfig(
            "Condrieu",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Blanc",
            prix = 56.0,
        ),
        BoissonConfig(
            "Saint-Peray",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Blanc",
            prix = 36.0,
        ),
        BoissonConfig(
            "Macon",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Blanc",
            prix = 28.0,
        ),
        BoissonConfig(
            "Chablis",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Blanc",
            prix = 29.50,
        ),
        BoissonConfig(
            "Gascogne",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Blanc",
            prix = 33.0,
        ),
        BoissonConfig(
            "Gascogne verre",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Blanc",
            prix = 8.0,
        ),
        BoissonConfig(
            "Viognier",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Blanc",
            prix = 28.50,
        ),
        // Vins Bouteilles - Bulles et Rosé
        BoissonConfig(
            "Champagne",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Bulles et Rosé",
            prix = 51.0,
        ),
        BoissonConfig(
            "Montagnieu",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Bulles et Rosé",
            prix = 26.0,
        ),
        BoissonConfig(
            "Rosé",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Bulles et Rosé",
            prix = 32.0,
        ),
        BoissonConfig(
            "Rosé verre",
            CategorieBoisson.VINS_BOUTEILLES,
            isGroupe = false,
            isNonGroupe = true,
            sousCategorie = "Bulles et Rosé",
            prix = 8.0,
        ),
        // Cafés
        BoissonConfig("Expresso", CategorieBoisson.CAFES, isGroupe = true, isNonGroupe = true, prix = 2.50),
        BoissonConfig("Allongé", CategorieBoisson.CAFES, isGroupe = true, isNonGroupe = true, prix = 2.50),
        BoissonConfig("Double", CategorieBoisson.CAFES, isGroupe = false, isNonGroupe = true, prix = 4.50),
        BoissonConfig("Crème", CategorieBoisson.CAFES, isGroupe = false, isNonGroupe = true, prix = 3.50),
        BoissonConfig("Thé", CategorieBoisson.CAFES, isGroupe = false, isNonGroupe = true, prix = 3.50),
    )
