name: Build APK

on:
  push:
    branches:
      - main  # Exécute ce workflow à chaque push sur la branche main
  pull_request:
    branches:
      - main  # Exécute ce workflow pour les pull requests vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérifier que le code est dans GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Installer Java
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      # Étape 3: Installer Android SDK
      - name: Install Android SDK
        run: |
          # Créer le répertoire pour Android SDK
          mkdir -p $HOME/android-sdk/cmdline-tools

          # Télécharger et extraire les outils de ligne de commande Android
          curl -L https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -o commandlinetools-linux.zip
          unzip commandlinetools-linux.zip -d $HOME/android-sdk/cmdline-tools
          rm commandlinetools-linux.zip

          # Déplacer les outils dans le répertoire correct
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/

          # Ajouter SDK à PATH
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

          # Vérification de sdkmanager
          if [ ! -f "$HOME/android-sdk/cmdline-tools/bin/sdkmanager" ]; then
            echo "Erreur : sdkmanager non trouvé"
            exit 1
          fi

          # Mettre à jour sdkmanager
          sdkmanager --update

      # Étape 4: Accepter les licences Android
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses

      # Étape 5: Installer les dépendances nécessaires
      - name: Install Android SDK dependencies
        run: |
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-34"
          sdkmanager "system-images;android-34;google_apis;x86_64"
          sdkmanager "emulator"

      # Étape 6: Construire le projet Android
      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew assembleRelease

      # Étape 7: Télécharger l'APK généré en tant qu'artéfact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
