name: Build APK

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Configure Java version 11

    - name: Set up Android SDK
      run: |
        echo "Setting up Android SDK..."
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip -d $HOME/Android
        echo "export ANDROID_SDK_ROOT=$HOME/Android" >> ~/.bashrc
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc
        yes | sdkmanager --licenses  # Accept all licenses

    - name: Install dependencies
      run: |
        ./gradlew dependencies  # Install dependencies

    - name: Build the APK
      run: |
        ./gradlew assembleRelease  # Build the APK in release mode

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3  # Use the latest version of the upload-artifact action
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk  # Path to your generated APK
