name: Build APK for Android

on:
  push:
    branches:
      - main  # Ou la branche que tu veux utiliser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install Android SDK
      run: |
        # Download command line tools
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O android-sdk.zip
        unzip android-sdk.zip -d $HOME/android-sdk/cmdline-tools
        rm android-sdk.zip

        # Install required packages
        echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --update
        echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-34"

        # Set environment variables for Android SDK
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        # Commande pour compiler ton APK
        ./gradlew assembleRelease

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk
